name: Linting, testing, building
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Setup node from node version file
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install modules
        run: npm install

      - name: Build a production project
        run: npm run build:prod

        if: always()
      - name: Lint Typescript
        run: npm run lint:ts

        if: always()
      - name: Lint CSS
        run: npm run lint:scss

        if: always()
      - name: Unit testing
        run: npm run test:unit

# TODO: figure out why screenshot tests fail in Github Actions
        if: always()
      - name: Build Storybook
        run: npm run storybook:build

        if: always()
      - name: UI screenshot testing
        run: npm run test:ui:ci
